# Generated by Django 5.2.11 on 2026-03-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('AI', 'AI'), ('Accounting', 'Accounting'), ('Office Automation', 'Office Automation'), ('AutoCAD', 'AutoCAD'), ('Multimedia', 'Multimedia'), ('Other', 'Other')], default='Software', max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=225, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('card_front', models.ImageField(blank=True, null=True, upload_to='cards/front/')),
                ('card_back', models.ImageField(blank=True, null=True, upload_to='cards/back/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('mobile_numbers', models.TextField(blank=True, default='[]', null=True)),
                ('addresses', models.TextField(blank=True, default='[]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
